# Generated by Django 5.0.4 on 2024-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_planet_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
