# Generated by Django 5.0.4 on 2024-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_planet_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='image',
        ),
        migrations.AddField(
            model_name='planet',
            name='gltf_file',
            field=models.FileField(blank=True, null=True, upload_to='planets/'),
        ),
    ]
