# Generated by Django 5.0.4 on 2024-04-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_remove_planet_image_planet_gltf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='gltf_file',
            new_name='usdz_file',
        ),
    ]
