# Generated by Django 5.0.4 on 2024-04-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_rename_gltf_file_planet_usdz_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='usdz_file',
            new_name='gltf_file',
        ),
    ]
