# Generated by Django 5.0.4 on 2024-04-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_rename_usdz_file_planet_gltf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='gltf_file',
        ),
        migrations.AddField(
            model_name='planet',
            name='object_url',
            field=models.TextField(default='https://example.com/default-planet-link'),
        ),
    ]
