# Generated by Django 5.0.4 on 2024-04-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_planet_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='flight.planet')),
            ],
        ),
    ]
