# Generated by Django 5.0.4 on 2024-04-14 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_planetbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='base_images')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flight.planetbase')),
            ],
        ),
    ]
