# Generated by Django 5.0.4 on 2024-04-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_baseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimage',
            name='base_description',
            field=models.TextField(default='base_description'),
        ),
    ]
