# Generated by Django 5.0.4 on 2024-04-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0011_baseimage_base_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseimage',
            name='base_description',
        ),
    ]
