# Generated by Django 5.0.4 on 2024-04-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0013_flightschedule_userbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='arrival_base',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='flight.planetbase'),
        ),
        migrations.DeleteModel(
            name='UserBooking',
        ),
    ]
