# Generated by Django 5.0.4 on 2026-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_flightschedule_arrival_base_delete_userbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='emoji',
            field=models.CharField(default='🪐', max_length=10),
        ),
    ]
