# Generated by Django 6.0.2 on 2026-02-19 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0015_planet_emoji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planet',
            options={'ordering': ['distance_from_earth_km']},
        ),
        migrations.RemoveField(
            model_name='planet',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='object_url',
        ),
        migrations.AddField(
            model_name='planet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='distance_from_earth_km',
            field=models.FloatField(default=0.0, help_text='Distance in millions of km'),
        ),
        migrations.AddField(
            model_name='planet',
            name='gltf_model_url',
            field=models.TextField(default='https://example.com/default-planet-link'),
        ),
        migrations.AddField(
            model_name='planet',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='travel_time_days',
            field=models.IntegerField(default=0, help_text='Travel time in days'),
        ),
        migrations.AddField(
            model_name='planet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('seats_total', models.IntegerField(default=100)),
                ('seats_available', models.IntegerField(default=100)),
                ('price_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='flight.planet')),
                ('origin_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='flight.planet')),
            ],
            options={
                'ordering': ['-departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_number', models.CharField(max_length=10)),
                ('pod_type', models.CharField(choices=[('standard', 'Standard'), ('luxury', 'Luxury'), ('cryo', 'Cryo Sleep')], default='standard', max_length=20)),
                ('price_credits', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='flight.flight')),
            ],
            options={
                'ordering': ['pod_type', 'pod_number'],
                'unique_together': {('flight', 'pod_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flight.flight')),
                ('pod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='flight.pod')),
            ],
            options={
                'ordering': ['-booked_at'],
                'unique_together': {('user', 'flight', 'pod')},
            },
        ),
    ]
