# Generated by Django 6.0.2 on 2026-02-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, default='')),
                ('passport_id', models.CharField(blank=True, default='', help_text='Space Passport ID', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('credits_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=14)),
                ('preferred_pod_type', models.CharField(choices=[('standard', 'Standard'), ('luxury', 'Luxury'), ('cryo', 'CryoSleep')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
